.travis.yml, package-lock.json, package.json, src/entrypoint.js, src/models/AppManager.js, src/models/Kernel.js, src/models/Stdlib.js, src/scripts/create-proxy.js, src/scripts/register.js, src/scripts/sync.js, src/scripts/unvouch.js, src/scripts/vouch.js, src/utils/contract.js, test/scripts/create-proxy.test.js
Artifacts require failed to fetch the contract when called
as a node module in another repo, as the working directory
was set to the parent's.
This change loads each contract manually from the build/
contracts directory, and provisions it with defaults.
=> Remove truffle artifacts from code

src/scripts/deploy.js, src/scripts/register.js, src/scripts/unvouch.js, src/scripts/vouch.js, src/zos-lib/kernel/KernelProvider.js, src/zos-lib/kernel/KernelWrapper.js
**MERGE AFTER #61** (change base branch to the [refactor branch](https://github.com/zeppelinos/zos-cli/tree/refactor_branch) before merging)
Following what I described in #60, this PR splits the kernel model into a wrapper and a provider.
Note there is no need of a deployer here, however we have that code spread somehow within the kernel project.
=> Split kernel model into a wrapper and a provider

README.md, src/models/AppController.js, src/scripts/add-implementation.js, test/scripts/add-implementation.test.js
Add-implementation no longer requires an alias option. If not set, it will default to the contract name.
=> Default alias to name in add-implementation

contracts/Imports.sol, contracts/mocks/ImplV1.sol, contracts/mocks/ImplV2.sol, src/commands/users/upgrade-proxy.js, src/models/AppController.js, src/models/NetworkAppController.js, src/scripts/upgrade-proxy.js, test/scripts/upgrade-proxy.test.js
Command upgrade-proxy will now upgrade all proxies for a given
contract alias if no address is specified. Also, if no contract
alias is set, and a --all flag is set, all contracts in the app
will be upgraded to the new version.
Fixes #33
=> Upgrade multiple proxies with a single command

src/commands/users/create-proxy.js, src/commands/users/upgrade-proxy.js, src/models/NetworkAppController.js, src/models/stdlib/Stdlib.js, src/scripts/create-proxy.js, src/scripts/upgrade-proxy.js, src/utils/digest.js, test/mocks/mock-stdlib-2/package.zos.test.json, test/mocks/mock-stdlib/package.zos.test.json, test/scripts/create-proxy.test.js, test/scripts/upgrade-proxy.test.js
This PR adds to the network package.zos file the bytecode of the
contract at the time it was deployed. It is then compared to the
bytecode of the contract locally before creating or upgrading a
proxy. If there was a change, then the command fails; this can be
overridden via a --force flag to either command.
Fixes #22.
=> Check modifications in contracts before add/upgrade proxy

README.md, examples/development.md
Removing the `--network` parameter from the README and examples since it's not needed.
Also fixes a broken link.
=> Remove network parameter from examples

src/commands/users/create-proxy.js, src/commands/users/init.js, src/commands/users/new-version.js, src/commands/users/upgrade-proxy.js
Removes the short version for opts that are not that frequent, in
order to improve readability of the commands used and avoid potential
mistakes from the users.
Removed the following short opts:
- -s for --stdlib
- -i for --init
- -a for --args
=> Remove short opts for readability

package-lock.json, package.json
I did this as cleanly as possible so that the commits can be reviewed one by one.
Additionally to the updates due to vulnerabilities, I updated `sha3` to the latest version which works with Node.js 10. I also commited the package-lock.json in the slightly different format which npm 6 generates.
After that, each commit corresponds to one update suggested by `npm audit`.
**Notice:** There are vulnerable dependencies which we can't get rid of until the next patch release of Truffle (see https://github.com/trufflesuite/truffle/issues/941).
=> Review dependency vulnerabilities as reported by `npm audit`

package-lock.json, package.json, src/bin/program.js, src/bin/zos-cli.js, src/models/network/NetworkBaseController.js, src/models/network/NetworkLibController.js, src/scripts/bump-version.js, src/scripts/create-proxy.js, src/scripts/link-stdlib.js, src/scripts/push.js, src/scripts/upgrade-proxy.js, src/utils/stdout.js, test/setup.js, truffle.js
Use new logger from lib which is silent by default, and pass through verbose and silent flags. Send data from commands to stdout when appropriate. Fixes #107.
=> Integrate new logger and log data to stdout

src/models/network/NetworkAppController.js, test/scripts/create-proxy.test.js, test/scripts/upgrade-proxy.test.js
Address is retrieved via `App.getImplementation`. There is a race condition if the app is being updated while the proxy is being created, but it is quite unlikely (and the CLI may probably break in other ways upon concurrent executions).
Fixes #153
=> Add implementation address in proxy information

contracts/mocks/ImplV1.sol, contracts/mocks/Invalid.sol, src/models/local/LocalBaseController.js, src/models/network/NetworkAppController.js, src/scripts/upgrade-proxy.js, test/helpers/captureLogs.js, test/scripts/add-implementation.test.js, test/scripts/create-proxy.test.js, test/scripts/upgrade-proxy.test.js
Checks whether an implementation has a constructor when adding it, an `initialize` method when creating a proxy for it (and not calling it), or a `migrate` method when upgrading it (and not calling it). Shows an error message in all cases, but does not halt execution, since there may be false positives (empty constructors, methods called initialize which are not initializers, migrations already called, etc).
Fixes #145
=> Check constructor, initialize, and migrate

package-lock.json, package.json, src/bin/program.js, src/commands/add-implementation.js, src/commands/bump-version.js, src/commands/create-proxy.js, src/commands/freeze.js, src/commands/init.js, src/commands/link-stdlib.js, src/commands/push.js, src/commands/status.js, src/commands/upgrade-proxy.js, src/scripts/add-implementation.js
- rename `--stdlib` option in `bump` command to `--link`. E.g: `zos bump 1.2.0 --link openzeppelin-zos@1.1.0`
- improve help message with differentiated main help with per-command help
- improve all commands and parameters help
- rename `--reupload` option in `push` command to `--reset`.
- make main help prettier
Fixes https://github.com/zeppelinos/zos-cli/issues/141
=> Improve help 

src/models/network/NetworkAppController.js
If contract name was set, and no proxies for it were found, then
the app would fail to report that no proxies were upgraded.
Fixes #176
=> Log there are no proxies found to upgrade when specifying contract

src/commands/create-proxy.js, src/commands/upgrade-proxy.js, src/utils/input.js, test/utils/input.test.js
When setting --args, if --init is not set, it will still invoke
the initializer with the default init method name. Affects create
and upgrade proxy.
Fixes #182
=> Args flag implies initialization in create and upgrade proxy

.travis.yml
We have had a few issues with regex incomatible between linux and
mac os, which the CI has failed to catch.
=> Build project on osx

src/commands/upgrade.js
The upgrade command was looking for `upgrade-proxy`, now renamed to `upgrade`.
=> Fixed upgrade script name in bin

contracts/Imports.sol, test/models/TestApp.test.js, test/scripts/create.test.js, test/scripts/push.test.js, test/scripts/upgrade.test.js
Fixes https://github.com/zeppelinos/zos-cli/issues/209
We don't need to use truffle artifacts for testing, we can use our `Contracts` objects
After this, we don't need to have the `Imports` contract anymore
=> Use zos-lib contracts instead of truffle artifacts for testing

src/commands/init.js
Fixes https://github.com/zeppelinos/zos-cli/issues/243
=> Rename `project` param to `project-name` for init command

src/bin/program.js, src/commands/session.js, src/scripts/session.js, src/utils/runWithTruffle.js, test/scripts/session.test.js
Fixes #122 
Commands like create, freeze, push, status and upgrade will use
<network> unless overriden.
Example:
zos session ropsten
Using "ropsten" as default network unless overriden.
...
zos push
zos create Foo
zos create ERC20 --network=notropsten
=> Introduce a 'zos session <network>' command.

src/models/local/LocalBaseController.js, src/scripts/bump.js, src/scripts/init-lib.js, src/scripts/init.js, src/scripts/link.js, src/scripts/push.js
~Fixes https://github.com/zeppelinos/zos-cli/issues/226~
Testing the app a bit I couldn't reproduce a scenario where this message was printed and no changes were made to any of the zos files. However, I noticed that while adding a contract, no message is being printed about that.
=> Add some logging lines

src/bin/errors.js, src/models/truffle/Truffle.js
1- Show error reason if loading truffle file fails. If the truffle file is invalid, no error description was shown. Now catches the file missing error and displays the zos init suggestion only then; and displays the error reason otherwise.
2- Display promise rejection via logger instead of throwing the exception. Otherwise a plain stack trace was shown.
=> Enhancements on error reporting

src/bin/program.js, src/commands/remove.js, src/models/files/ZosNetworkFile.js, src/models/files/ZosPackageFile.js, src/models/local/LocalBaseController.js, src/models/network/NetworkAppController.js, src/models/network/NetworkBaseController.js, src/models/network/NetworkLibController.js, src/scripts/remove.js, src/scripts/status.js, test/scripts/push.test.js, test/scripts/remove.test.js, test/scripts/status.test.js
Removes a command from the zos.json file. Network controller now
also checks for contracts missing from the zos.json file and
schedules them for removal from the app.
Fixes #154
=> Add new remove command

src/commands/compare.js, src/commands/create.js, src/commands/freeze.js, src/commands/init.js, src/commands/link.js, src/commands/pull.js, src/commands/push.js, src/commands/status.js, src/commands/upgrade.js, src/utils/runWithTruffle.js
Add new --timeout flag to all commands that interact with the
blockchain, which is used for timing out on transactions (not
deployments).
Fixes https://github.com/zeppelinos/zos-lib/issues/149
=> Add transactions timeout to all commands

package-lock.json, package.json, src/bin/zos-cli.js
Use npm/lockfile to acquire unique lock on a .zos.lock local file and exit the CLI if cannot. Fixes #168.
=> Ensure no more than one instance of CLI is running simultaneously

package.json, src/models/network/NetworkAppController.js, src/models/stdlib/Stdlib.js, src/models/stdlib/StdlibProvider.js, test/mocks/packages/package-with-stdlib-range.zos.json, test/models/Stdlib.test.js, test/scripts/link.test.js, test/scripts/push.test.js
An stdlib version can now be set using npm semver range syntax,
such as ^1.0.0 or ~1.3.0. When linking to a stdlib, the zos.json
file will store the range requirement, and the zos.network.json
file will act as a sort of "lock", storing the actual version
used for deployment. If the actual version does not match the
requirement, an error is thrown.
Fixes #217
=> Allow stdlib versions to be specified with npm range syntax

src/commands/add.js, src/commands/bump.js, src/commands/compare.js, src/commands/create.js, src/commands/freeze.js, src/commands/init.js, src/commands/link.js, src/commands/pull.js, src/commands/push.js, src/commands/remove.js, src/commands/session.js, src/commands/status.js, src/commands/upgrade.js, src/models/network/Session.js, src/scripts/session.js, src/utils/runWithTruffle.js, test/scripts/session.test.js
- Use session defaults in commands with --push option. Network session was not being considered. Now the value for --push is optional, and is loaded from the session network if present.
- Add --timeout option to commands with --push option. The timeout gets passed to the push action if called.
- Support `from` and `timeout` options in `Session` command. Handle more options in the session model, which are merged into the options passed by runWithTruffle. Also, added support for expires to choose for how many seconds the session is valid. Fixes #297.
- Add alias `-n` for network option in session command.
- Handle network related options from `runWithTruffle` wrapper. This ensures that network is correctly passed down to the scripts, as runWithTruffle checks the current session always. …
=> Session command fixes and improvements

src/commands/compare.js, src/models/status/EventsFilter.js, src/models/status/StatusReport.js
- Removes `--timeout` option (Fixes #308)
- Renames expected and actual to on-chain and local (Fixes #309)
- Fixes `EventsFilter` to clear timeout when the main promise resolves, which caused compare and pull to hang (Fixes #307)
=> Fix compare command

changelog.md, src/scripts/status.js, test/scripts/status.test.js
=> Review wording on contract to be removed when running status

changelog.md, src/models/TestApp.js, test/models/TestApp.test.js
Given that txParams is to be used more frequently than the network file object, txParams was moved to the first one. Fixes #333.
=> Swapped params of TestApp initializer

changelog.md, src/commands/index.js, src/commands/session.js, src/commands/update.js, src/models/network/NetworkAppController.js, src/scripts/update.js, test/scripts/update.test.js
The update command related files were wrongly named. This PR renames these files (command, scripts and test files). I'm also using update instead of upgrade in many outputted messages
=> Polish update command files

src/models/network/NetworkAppController.js, src/models/network/NetworkBaseController.js, test/scripts/create.test.js
Creating a proxy for a contract that belongs to an stdlib that was
linked, but that link was not pushed to the network, would yield
a "VM Revert" error. Now it explains that the stdlib is linked but
a push is missing.
Fixes #218
=> Fail with explicit error when creating proxy for missing stdlib

changelog.md, package-lock.json, package.json, src/commands/index.js, src/commands/verify.js, src/models/Verifier.js, src/models/local/LocalBaseController.js, src/models/network/NetworkBaseController.js, src/scripts/verify.js, src/utils/contracts.js, test/scripts/verify.test.js
Fixes https://github.com/zeppelinos/zos-cli/issues/274
This is the first approach to a possible implementation of a contract verification on  [etherchain](https://www.etherchain.org). I still have to code some integration tests for the etherchain communication workflow part.
Some validations have been implemented in order to forbid a user to try to verify a contract without first initializing, adding and pushing a contract to a network so we can retrieve the contract address from the zos._network_.json file. Consider that etherchain only allows contract verification and publish on the mainnet, so if  other network is specified an error (_Unable to retrieve the contract creation bytecode_) will be thrown.
=> Verify contracts command

src/commands/create.js, src/models/files/ZosNetworkFile.js, src/models/network/NetworkAppController.js, src/models/network/NetworkBaseController.js, src/models/network/NetworkLibController.js, src/models/status/StatusFetcher.js, src/scripts/create.js, test/models/StatusComparator.test.js, test/models/StatusFetcher.test.js, test/scripts/create.test.js, test/scripts/status.test.js, test/scripts/update.test.js
Fixes https://github.com/zeppelinos/zos-lib/issues/32
Analyzing this issue a bit, I thought about two alternatives:
The idea of this approach is to allow users to create instances of any contract they have already registered in their `App`s. 
**PRO:** We will be using exactly the same on-chain bytecode
**CON:** Currently, every non-upgradeable instance will follow the current initializers model. This means, even if a user could create an instance of a contract using a constructor function, given that we are registering only contracts without constructors, we will be forcing them to work with initializers.
This approach could allow users to create instances of any contract they have locally. 
**PRO:** It will allow users to work with constructors instead of the current initializer model. …
=> Support creating non-upgradeable contract instances

.gitignore, changelog.md, src/models/lib/PackageAtVersion.js, src/models/status/StatusChecker.js, src/models/status/StatusComparator.js, src/models/status/StatusFetcher.js, test/models/StatusComparator.test.js, test/models/StatusFetcher.test.js
- Adds new abstraction PackageAtVersion, that represents a package with a specific version as default (we could move it to zos-lib).
- Replicates all tests for app and lib (where appropriate) for status fetcher and comparator.
I strongly suggest to review this PR with whitespace diff disabled
Fixes #314
=> Fix status compare and status fetch for libs
