package-lock.json
package.json
scripts/register.js
scripts/unvouch.js
scripts/vouch.js

Fixes https://github.com/zeppelinos/labs/issues/83
This PR provides 3 scripts to interact with the zOS Kernel:
- Registering new releases
- Vouching
- Unvouching

Kernel CLI

---

package-lock.json
package.json
src/models/AppManager.js

Adapts to zos-lib PR #73 also named fix-decodeLogs-1
https://github.com/zeppelinos/zos-lib/pull/73

Fix usage of decodeLogs

---

package-lock.json
package.json
src/utils/runWithTruffle.js

*This PR is already pointing to the refactor branch we will be working on*
Fixes #32 
The idea was to use Truffle Environment to get a web3 provider and artifacts. 
Then, we have a `runWithTruffle` function to execute those scripts that require to be run within such context.

Remove truffle exec

---

bin/developers.js
bin/users.js
bin/vouching.js
bin/zos-cli.js
src/commands/developers/deploy.js
src/commands/developers/init-distribution.js
src/commands/developers/register.js
src/commands/users/add-implementation.js
src/commands/users/create-proxy.js
src/commands/users/deploy-all.js
src/commands/users/init.js
src/commands/users/set-stdlib.js
src/commands/users/sync.js
src/commands/users/upgrade-proxy.js
src/commands/vouching/unvouch.js
src/commands/vouching/vouch.js
src/scripts/deploy-all.js
src/scripts/deploy.js
src/scripts/init-distribution.js
src/scripts/init.js

**MERGE AFTER #55** (change base branch to the [refactor branch](https://github.com/zeppelinos/zos-cli/tree/refactor_branch) before merging)
Fixes #6 
Related to #9
This PR introduces a new entry point for each command. It allows us to use truffle just when needed and build custom helpers for each command.

Build one entry point for each command

---

src/models/FileSystem.js
src/models/Stdlib.js
src/utils/PackageFilesInterface.js
src/utils/environment.js
src/zos-lib/ProjectDeployer.js
src/zos-lib/stdlib/StdlibDeployer.js
src/zos-lib/stdlib/StdlibProvider.js
test/models/AppManager.test.js
test/scripts/deploy-all.test.js
test/scripts/init.test.js
test/scripts/sync.test.js

**MERGE AFTER #66** (change base branch to the [refactor branch](https://github.com/zeppelinos/zos-cli/tree/refactor_branch) before merging)
This PR adds a new FileSystem model wrapping fs module functionality. It allows us to read, parse and write files more friendly.

Model a file system wrapper

---

README.md
examples/development.md
examples/kernel.md
examples/testing.md
examples/vouching.md

Solves https://github.com/zeppelinos/zos-cli/issues/84

Refactor README.md

---

src/bin/errors.js
src/bin/zos-cli.js
src/models/AppController.js
src/models/ErrorHandler.js
src/models/NetworkAppController.js
src/models/stdlib/Stdlib.js
src/models/stdlib/StdlibProvider.js
src/scripts/add-implementation.js
src/scripts/create-proxy.js
src/scripts/deploy.js
src/scripts/init-distribution.js
src/scripts/init.js
src/scripts/new-version.js
src/scripts/register.js
src/scripts/set-stdlib.js
src/scripts/unvouch.js
src/scripts/upgrade-proxy.js
src/scripts/vouch.js
src/utils/ContractsProvider.js
src/utils/runWithTruffle.js

Improve error handling

---

package-lock.json
package.json
src/commands/users/add-implementation.js
src/models/AppController.js
src/scripts/add-all-implementations.js
src/scripts/add-implementation.js
test/scripts/add-all-implementations.test.js
test/scripts/add-implementation.test.js
test/scripts/create-proxy.test.js
test/scripts/new-version.test.js
test/scripts/status.test.js
test/scripts/upgrade-proxy.test.js

Support adding multiple implementations

---

src/commands/developers/deploy.js
src/commands/users/add-implementation.js
src/commands/users/create-proxy.js
src/commands/users/init.js
src/commands/users/new-version.js
src/commands/users/set-stdlib.js
src/commands/users/sync.js
src/commands/users/upgrade-proxy.js
src/scripts/upgrade-proxy.js

Support syncing in multiple commands

---

package.json
src/commands/users/sync.js
src/utils/runWithTruffle.js

Addresses https://github.com/zeppelinos/zos-cli/issues/39.

Compile contracts before sync

---

src/models/NetworkAppController.js

Provide an useful CTA to the user.

Improve logging

---

test/.mocha.opts
test/models/ProjectDeployer.test.js
test/models/Stdlib.test.js
test/scripts/add-all-implementations.test.js
test/scripts/add-implementation.test.js
test/scripts/create-proxy.test.js
test/scripts/init.test.js
test/scripts/link-stdlib.test.js
test/scripts/new-version.test.js
test/scripts/push-with-stdlib.test.js
test/scripts/push.test.js
test/scripts/status.test.js
test/scripts/upgrade-proxy.test.js
test/setup.js

Remove mocha opts in favour of requiring setup file manually

---

.gitignore
package-lock.json
package.json
src/models/ProjectDeployer.js
src/models/network/NetworkAppController.js
src/models/stdlib/StdlibDeployer.js

Fixes #104 
Related to https://github.com/zeppelinos/zos-lib/pull/119
CI is failing cause I to release a new version of zos-lib first

Stdlib deployer should use releases

---

src/bin/errors.js

Fixes https://github.com/zeppelinos/zos-cli/issues/155

Handle unknown commands

---

src/commands/create-proxy.js
src/commands/upgrade-proxy.js
src/models/network/NetworkAppController.js
src/utils/input.js
test/utils/input.test.js

Use the same strategy as remix in parsing input parameters. Note
that the remix code had a bug in the regex, which is fixed here.
Fixes #156

Parse input args as JSON

---

src/commands/init.js
src/models/local/LocalBaseController.js
src/models/local/LocalLibController.js
src/scripts/init-lib.js
src/scripts/init.js
test/scripts/init-lib.test.js
test/scripts/init.test.js

Add force option to init command

---

src/models/network/NetworkBaseController.js

Lib is already reporting implementation address

Remove redundant log entry

---

src/index.js

~**MERGE AFTER #184**~ Ready to merge.

Export TestApp and other models for scripting and testing

---

src/models/network/NetworkLibController.js
test/scripts/push.test.js

Do not allow contract pushes on frozen libs

---

src/commands/init.js

Related to https://github.com/zeppelinos/zos-cli/issues/195

Clarify init help

---

README.md

fixes https://github.com/zeppelinos/zos-cli/issues/195

Clarify "Setup your project" section in README

---

src/utils/input.js
test/utils/input.test.js

I'm removing look-behinds since it's not supported on Mac :/

Fix input parsing regexs

---

contracts/mocks/ImplV2.sol
src/bin/errors.js
src/commands/add.js
src/commands/push.js
src/commands/status.js
src/models/ErrorHandler.js
src/models/local/LocalBaseController.js
src/models/network/NetworkAppController.js
src/models/truffle/Truffle.js
src/models/truffle/TruffleInitializer.js
src/scripts/status.js
src/scripts/upgrade.js
src/utils/runWithTruffle.js
test/models/Truffle.test.js
test/scripts/upgrade.test.js

Fixes https://github.com/zeppelinos/zos-cli/issues/205 and other stuff :)

Multiple improvements

---

src/models/truffle/Truffle.js

Fixes https://github.com/zeppelinos/zos-cli/issues/224

Fix Truffle folders initialization

---

src/models/network/NetworkAppController.js

Fixes https://github.com/zeppelinos/zos-cli/issues/225
I'd love to add a test, but it will be easier once we have the [EventFilter](https://github.com/zeppelinos/zos-cli/pull/261/files#diff-15) merged

Do not set Stdlib to zero if not necessary

---

src/scripts/status.js
test/helpers/captureLogs.js

Fixes https://github.com/zeppelinos/zos-cli/issues/213

Improve status command logging colors

---

src/models/network/NetworkAppController.js
src/models/network/NetworkLibController.js
test/scripts/create.test.js

Fixes https://github.com/zeppelinos/zos-cli/issues/206

Store proxy address in contract build files

---

src/models/stdlib/StdlibProvider.js
test/models/Stdlib.test.js

Fixes https://github.com/zeppelinos/zos-cli/issues/227

Improve StdlibProvider error handling

---

.gitignore
src/commands/session.js
src/models/local/LocalBaseController.js
src/models/network/Session.js
src/scripts/session.js
src/utils/runWithTruffle.js
test/scripts/session.test.js

Polish session command

---

src/bin/program.js
src/commands/pull.js
src/models/files/ZosNetworkFile.js
src/models/files/ZosPackageFile.js
src/models/local/LocalBaseController.js
src/models/network/NetworkBaseController.js
src/models/status/StatusChecker.js
src/models/status/StatusComparator.js
src/models/status/StatusFetcher.js
src/scripts/compare.js
src/scripts/pull.js
test/models/StatusComparator.test.js
test/models/StatusFetcher.test.js

Fixes https://github.com/zeppelinos/zos-cli/issues/31
Depends on #261

Add pull command

---

package-lock.json
package.json
src/models/local/LocalBaseController.js
src/models/network/NetworkAppController.js
src/models/network/NetworkLibController.js
src/models/network/Session.js
src/models/status/StatusFetcher.js
src/models/status/StatusReport.js
src/scripts/status.js
test/helpers/captureLogs.js
test/models/StatusComparator.test.js
test/models/StatusFetcher.test.js
test/scripts/create.test.js
test/scripts/push.test.js

Update codebase using zos-lib 1.2

---

package.json
test/setup.js

Fixes https://github.com/zeppelinos/zos-lib/issues/121

Set ENV in tests setup file

---

src/bin/errors.js
src/bin/program.js
src/bin/zos-cli.js
src/commands/add.js
src/commands/bump.js
src/commands/compare.js
src/commands/create.js
src/commands/freeze.js
src/commands/index.js
src/commands/init.js
src/commands/link.js
src/commands/pull.js
src/commands/push.js
src/commands/remove.js
src/commands/session.js
src/commands/status.js
src/commands/upgrade.js

Closes #56 
Closes #252 
I addressed #56 here too since it was affecting just commands files

Polish commands declaration

---

test/helpers/cleanup.js
test/models/Truffle.test.js
test/scripts/init-lib.test.js
test/scripts/init.test.js

Continuation of https://github.com/zeppelinos/zos-cli/pull/229

Update tmp files cleanup

---

src/scripts/status.js

Sorry I went ahead and created a PR without asking first. I was looking to see if I can find the problem, and saw it was a minor fix.
Fixes #291

Fix status version info log level

---

package-lock.json
package.json
test/mocks/mock-stdlib-undeployed/contracts/GreeterImpl.sol
test/mocks/mock-stdlib-undeployed/package.json
test/mocks/mock-stdlib-undeployed/truffle.js
test/mocks/mock-stdlib-undeployed/zos.json
test/mocks/packages/package-with-undeployed-stdlib.zos.json
test/scripts/push.test.js

Adds test for #296 which was not reproducible, so this PR adds a test to ensure it works.

Add test for error message upon undeployed stdlib

---

changelog.md
src/bin/options.js
src/bin/program.js
src/commands/add.js
src/commands/bump.js
src/commands/create.js
src/commands/freeze.js
src/commands/init.js
src/commands/link.js
src/commands/push.js
src/commands/remove.js
src/commands/session.js
src/commands/status.js
src/commands/upgrade.js
src/utils/runWithTruffle.js

Refactor common options into helpers. Also fixes #302.

Refactor command options

---

package.json
src/commands/init.js
src/commands/push.js
src/commands/session.js
test/commands/add.test.js
test/commands/bump.test.js
test/commands/create.test.js
test/commands/freeze.test.js
test/commands/init.test.js
test/commands/link.test.js
test/commands/push.test.js
test/commands/remove.test.js
test/commands/session.test.js
test/commands/share.js
test/commands/status.test.js
test/commands/update.test.js
test/setup.js

Add tests for commands parsing and option handling
